workflows:
  eas-android:
    name: "EAS Android Build"
    environment:
      node: 18
      java: 11
      groups:
        - expo-tokens
    scripts:
      - name: Install dependencies
        script: |
          npm install -g eas-cli
          npm install
      - name: Check Expo login
        script: |
          eas whoami || eas login --token $EXPO_TOKEN
      - name: Build Android debug (No Keystore)
        script: |
          eas build -p android --profile preview
    artifacts:
      - build/**/*.apk
